### ISSUE TITLE
[NESTJS][Mikro-ORM]  RangeError: Maximum call stack size exceeded

### ISSUE THREAD

**Issue by Nashar410** [nartc/mapper#436] opened 2022-03-21 18:43 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Describe the issue

Hello ! 

At first, thank you for all the work done, and especially your doc !

As you can imagine, I have a problem, that I was able to identify while doing the reproduction of the bug.

It seems that the `Collection` object from `@mikro-orm/core` is causing this error :

```bash
RangeError: Maximum call stack size exceeded
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:25:33)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
    at getPathRecursive (my-project/packages/core/src/lib/initialize-utils/get-path-recursive.util.ts:62:28)
```

After a few attempt to reproduce the bug, I found that it only occurs at the very second I try to map my DTO to my Entity (as shown in the `StudenProfile` below). 

A humble repo to reproduce the behavior (I did not have the time to provide a docker database to connect to, but I can if needed) : https://github.com/Nashar410/automapper-nestjs-bug-repro

Can someone help me ?

Thank you again !

### Models/DTOs/VMs

```typescript
import { AutomapperProfile, InjectMapper } from '@automapper/nestjs';
import type { Mapper } from '@automapper/core';
import { Injectable } from '@nestjs/common';
import { Student } from '../entities/student.entity';
import { StudentDto } from '../dto/student.dto';

@Injectable()
export class  StudentProfile extends AutomapperProfile {
    constructor(
        @InjectMapper() mapper: Mapper
    ) {
        super(mapper);
    }
    
    mapProfile() {
        return (mapper) => {
            mapper.createMap(Student, StudentDto); // <---- is working !
            mapper.createMap(StudentDto, Student); // <---- Causing RangeError: Maximum call stack size exceeded
            
        };
    }
}
```

Here my Entity : 

```typescript
import { AutoMap } from "@automapper/classes";
import { TestRoom } from "./test-room.entity";
import { Test } from "./test.entity";
import { Collection } from '@mikro-orm/core';


export class Student {

    @AutoMap()
    id: string;

    @AutoMap()
    name: string;

    @AutoMap({ typeFn: () => TestRoom })
    hasBeen = new Collection<TestRoom>(this);

    @AutoMap({ typeFn: () => Test })
    hasSucceed = new Collection<Test>(this);

}
```
Here my DTO :

```typescript
import { AutoMap } from "@automapper/classes";
import { TestRoomDto } from "./test-room.dto";
import { TestDto } from "./test.dto";

export class StudentDto {

    @AutoMap()
    id: string;

    @AutoMap()
    name: string;

    @AutoMap({ typeFn: () => TestRoomDto })
    hasBeen: TestRoomDto[];

    @AutoMap({ typeFn: () => TestDto })
    hasSucceed: TestDto[];

}
```

### Steps to reproduce

1. npm i
2. npm run start

### Expected behavior

To not have the RangeError.

### Minimum reproduction code

https://github.com/Nashar410/automapper-nestjs-bug-repro

### Package

- [ ] I don't know.
- [X] <code>@automapper/core</code>
- [X] <code>@automapper/classes</code>
- [X] <code>@automapper/nestjs</code>
- [ ] <code>@automapper/pojos</code>
- [ ] <code>@automapper/sequelize</code>
- [ ] <code>@automapper/types</code>
- [ ] Other (see below)

### Other package and its version

@mikro-orm/core": "^5.1.1

### AutoMapper version

7.3.14

### Additional context

Here my Stack (from package.json): 
- NestJs :
```json
    "@nestjs/common": "^8.0.0",
    "@nestjs/core": "^8.0.0",
    "@nestjs/mapped-types": "*",
    "@nestjs/platform-express": "^8.0.0",
    "reflect-metadata": "^0.1.13",
```
- Mikro-Orm : 
```json
    "@mikro-orm/core": "^5.1.1",
```
- Automapper : 
```json
    "@automapper/classes": "^7.3.14",
    "@automapper/core": "^7.3.14",
    "@automapper/nestjs": "^7.3.14",
```

**Comment by Nashar410** [comment] 2022-03-22 00:18
> Hi @Nashar410, thanks for reporting. What are the steps I need to do in the reproduce sample to get to the error?

Hi ! Thanks for responding.

It occurs as soon as you launch the app (with npm run start) in the minimal repo.

Otherwise, it happens when the Mikro-orm's entity have a Collection as a type.

**Comment by nartc** [comment] 2022-04-04 02:55
@Nashar410 Sorry for the late response. After taking a closer look at the code for v7, I deem this one as `won't fix`. AutoMapper v7 relies heavily on `instantiating` a new class, fixing this requires a lot of effort trying to rework the `mikro()` plugin. However, in v8, this doesn't seem to be an issue (at least I couldn't reproduce this on v8). I'd suggest [migrating to AutoMapper v8](https://automapperts.netlify.app/docs/getting-started/migrate-to-automapper-v8).

If you run into issues with v8, please open a new issue.

**Closed by nartc** 2022-04-04 02:55 UTC
Labels: bug
