### ISSUE TITLE
Is the NPM package broken ? There is no dist folder in it.

### ISSUE THREAD

**Issue by nvdnkpr** [nartc/mapper#125] opened 2020-05-09 21:15 UTC
Also there version number seems to be 1.1.X. So where is the  announced (v)6

**Comment by nartc** [comment] 2020-05-09 21:17
Sorry for the inconvenience. This is the 2nd time that it happens. I’ll take a look asap.

**Comment by nvdnkpr** [comment] 2020-05-09 21:17
No problem, just wanted to tell you since it's a cool package. Playing with it along other tools.

**Comment by nvdnkpr** [comment] 2020-05-09 21:18
Guess the version thing is the same issue...

**Comment by nvdnkpr** [comment] 2020-05-09 21:24
You seem to use semantic-release (👍 ), so the version number get incremented automatically. However, I would suggest you use the version number 0.0.0 which generally means that you semantically release. Also npm would then complain instead of allowing you to publish your package.

**Comment by nartc** [comment] 2020-05-09 21:38
@nvdnkpr Thanks for the suggestion. Can you please give it a try now? I can install the package locally now.

**Comment by nartc** [comment] 2020-05-09 21:39
And thanks for the kind words. It'd be super helpful if you could throw any idea for the library my way.

**Comment by nvdnkpr** [comment] 2020-05-09 21:50
That's the least I can do. 

I tried to install it, with the same result. Are you on gitter ? I think I might have found your problem.

**Comment by nartc** [comment] 2020-05-09 21:52
I'm not on gitter but I'm on Discord (Chau#9478)

**Comment by nvdnkpr** [comment] 2020-05-09 21:53
ok wait a min :)

**Comment by nartc** [comment] 2020-05-10 01:09
@nvdnkpr it seems that the issue is consumer's error. I'll close this issue. Thanks again

**Closed by nartc** 2020-05-10 01:09 UTC
Labels: awaiting reply
