### ISSUE TITLE
Strange behaviour when test coverage active.

### ISSUE THREAD

**Issue by rifatdover** [nartc/mapper#228] opened 2020-11-28 22:24 UTC
## I'm submitting a...

<pre><code>
[ ] Regression 
[X] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
I think this is happening because istanbul adds some extra fields for calculating coverage. 
Gives errors related to some fields are not mapped. 

Also some mapping not executed. Have you met any issue related that?

## Expected behavior
Should work same without coverage active

## Environment

<pre><code>
Version: X.Y.Z
 
For Tooling issues:
- Node version: XX  
- Platform:  

Others:

</code></pre>

**Comment by nartc** [comment] 2020-11-30 03:18
Hi @rifatdover , can you provide a sample reproduce?

**Comment by caiopiassali** [comment] 2020-12-27 00:27
I have a similar issue using this package under [NestJSX Automapper](https://github.com/nestjsx/automapper) wrapper and NestJS.

When I run my application, automapper works as expected. But when I run it inside test files with jest some mapping errors occurs.

Here is my code:
```javascript
// base.ts
class Base {
  @AutoMap()
  id!: string;
}

// user.ts
class User extends Base {
  @AutoMap()
  username!: string;
}

// post.ts
class Post extends Base {
  @AutoMap()
  title!: string;

  @AutoMap()
  image!: string;

  @AutoMap()
  imageThumb!: string;

  @AutoMap()
  tags!: string[];

  @AutoMap()
  author!: User;

  @AutoMap()
  createdAt: Date = new Date();
}

// post-reaction.ts
class PostReaction extends Base {
  post!: Post;

  user!: User;
}

// author-result.ts
class AuthorResult {
  constructor(
    public readonly id: string,
    public readonly username: string
  ) {
  }
}

// post-result.ts
class PostResult {
  constructor(
    public readonly id: string,
    public readonly title: string,
    public readonly image: string,
    public readonly imageThumb: string,
    public readonly tags: string[],
    public readonly author: AuthorResult,
    public readonly createdAt: Date
  ) {
  }
}

// post-reaction-result.ts
class PostReactionResult {
  constructor(
    public readonly id: string,
    public readonly user: string,
    public readonly username: string
  ) {
  }
}
```

And my Profile class:
```javascript
// post-profile.ts
class PostProfile extends ProfileBase {
  constructor(mapper: AutoMapper) {
    super();

    mapper.createMap(User, AuthorResult);
    mapper.createMap(Post, PostResult)
      .forMember(dest => dest.author, mapWith(AuthorResult, src => src.author));
    mapper.createMap(PostReaction, PostReactionResult)
      .forMember(dest => dest.user, mapFrom(src => src.user.id))
      .forMember(dest => dest.username, mapFrom(src => src.user.username));
  }
}
```

And finally, my test file:
```javascript
// post-profile.spec.ts
describe('PostProfile', () => {
  const mapper = new AutoMapper();
  mapper.addProfile(PostProfile);

  it('should map User to AuthorResult successfully', () => {
    const user = new User();
    user.id = 'userId';
    user.username = 'username';

    const result = mapper.map(user, AuthorResult);

    expect(result).toEqual({
      id: user.id,
      username: user.username
    });
  });

  it('should map Post to PostResult successfully', () => {
    const user = new User();
    user.id = 'userId';
    user.username = 'username';
    const post = new Post();
    post.id = 'id';
    post.title = 'title';
    post.image = 'image.jpg';
    post.imageThumb = 'thumb.jpg';
    post.tags = ['Tag 1', 'Tag 2'];
    post.author = user;

    const result = mapper.map(post, PostResult);

    expect(result).toEqual({
      id: post.id,
      title: post.title,
      image: post.image,
      imageThumb: post.imageThumb,
      tags: post.tags,
      createdAt: post.createdAt,
      author: {
        id: user.id,
        username: user.username
      }
    });
  });

  it('should map PostReaction to PostReactionResult successfully', () => {
    const user = new User();
    user.id = 'userId';
    user.username = 'username';
    const post = new Post();
    const postReaction = new PostReaction();
    postReaction.id = 'id';
    postReaction.user = user;
    postReaction.post = post;

    const result = mapper.map(postReaction, PostReactionResult);

    expect(result).toEqual({
      id: postReaction.id,
      user: user.id,
      username: user.username
    });
  });
});
```

Here is the error output from jest.
```javascript
Summary of all failing tests
 FAIL  src/post.profile.spec.ts (19.077s)
  ● PostProfile › should map Post to PostResult successfull

    Error mapping:
    - Source: class Post extends entities_1.Base {
      constructor() {
        /* istanbul ignore next */
        cov_2cxuu3kzjc().f[0]++;
        cov_2cxuu3kzjc().s[8]++;
        super(...arguments);

        /* istanbul ignore next */
        cov_2cxuu3kzjc().s[9]++;
        this.createdAt = new Date();
      }

    }
    - Destination: class PostResult {
        constructor(id, title, image, imageThumb, tags, author, createdAt) {
            this.id = id;
            this.title = title;
            this.image = image;
            this.imageThumb = imageThumb;
            this.tags = tags;
            this.author = uploadedBy;
            this.createdAt = createdAt;
        }
    }

    Unmapped properties:
    -------------------
    author,
    f

      34 |     post.author = user;
      35 | 
    > 36 |     const result = mapper.map(post, PostResult);
         |                           ^
      37 | 
      38 |     expect(result).toEqual({
      39 |       id: post.id,

      at map (../../node_modules/@nartc/automapper/src/core/map.ts:242:13)
      at AutoMapper.map$1 [as map] (../../node_modules/@nartc/automapper/src/automapper.ts:179:12)
      at Object.<anonymous> (src/post.profile.spec.ts:36:27)

  ● PostProfile › should map PostReaction to PostReactionResult successfully


    Error mapping:
    - Source: class PostReaction extends entities_1.Base {}
    - Destination: class PostReactionResult {
        constructor(id, user, username) {
            this.id = id;
            this.user = user;
            this.username = username;
        }
    }

    Unmapped properties:
    -------------------
    user,
    username,
    f

      58 |     postReaction.user = user;
      59 | 
    > 60 |     const result = mapper.map(postReaction, PostReactionResult);
         |                           ^
      61 | 
      62 |     expect(result).toEqual({
      63 |       id: postReaction.id,

      at map (../../node_modules/@nartc/automapper/src/core/map.ts:242:13)
      at AutoMapper.map$1 [as map] (../../node_modules/@nartc/automapper/src/automapper.ts:179:12)
      at Object.<anonymous> (src/post.profile.spec.ts:60:27)


Test Suites: 1 failed, 37 passed, 38 total
Tests:       2 failed, 108 passed, 110 total
Snapshots:   0 total
Time:        47.452s
Ran all test suites.
```

## Environment
```
Version: "7.0.4"
 
For Tooling issues:
- Node version: v12.16.2
- Platform: Windows 10 Pro x64

Others:
- NestJS version: "^7.0.0"
- Typescript version: "3.8.3"
- Jest version: "25.2.3"
```

If created mapper is a basic mapper it works well. But with additional mapping configuration, like **forMember** or **mapWith**, the mapping errors occurs.

And in all error cases mapper tried to map a 'f' property, but it don't exists in any class and is not defined in any mapping configuration.

**Comment by nartc** [comment] 2020-12-27 02:49
@rifatdover Thanks for providing the info. I'll take a look tomorrow.

**Comment by nartc** [comment] 2021-01-04 19:36
I'm going to test this one out again today with `@automapper/nestjs`.

**Comment by nartc** [comment] 2021-01-05 00:10
@rifatdover @caiopiassali I believe this has been fixed with `@automapper/*` latest beta release. I also added a sample profile test here (https://github.com/nartc/mapper/blob/main/packages/nestjs-integration-test/src/app/profiles/address.profile.spec.ts). If you have been following this repo, you'd know that I've broken up `@nartc/automapper` into `@automapper/*` with plugin-based approach. `1.0.0-beta.4` is the latest beta now. Feel free to give it a try and give the docs: https://automapperts.netlify.app a look as well.

One problem is that for `mapFrom()`, `forMember()` etc... anything that uses **Selector** to grab a property path (eg: `d => d.foo.bar`) won't be caught by Coverage because those `d => d.foo.bar` are never actually executed. AutoMapper mainly converts the function to `string` then use regex to extract the property path (eg: `foo.bar` will be extracted in this case). Thus, I'd suggest to ignore `Profile` from your coverage and only test the result of `map()`. 

What do you guys think? Any suggestions?

**Comment by caiopiassali** [comment] 2021-01-05 03:21
@nartc i've tested with latest release 1.0.0-beta.4 and now it works fine.

About test coverage, in my case I don't care about those lines that will not be caught. Only test the result of ```map()``` for me is enough and with this beta version this is working well.

In the migration from the old version to the new, I noticed some changes that I will miss.

- The first was the removal of ```skipUnmappedAssertion``` option: In my case I expect to have many partial mappings, cases that I don't want to map all properties in destination and add ```ignore()``` configuration in all properties to avoid ```Unmapped Properties``` error will be a lot of work.
- And also the need to inform ```source``` type when call ```map()```. In older versions mapping worked with only two arguments, ```sourceObj``` and ```destination``` type, which made this package incredible. Now I needed to add ```source``` type in all ```map()``` calls.

There was a specific reason for these changes?

Thanks in advance for your attention.

**Comment by nartc** [comment] 2021-01-05 03:32
@caiopiassali 
1. `skipUnmappedAssertion` was put in place for preventing a thrown exception leading to an app crash. Since default `ErrorHandler#handle` is just a `console.error` now, it's not needed. Granted, you'll still see the unampped errors. If that's not something you'd like to see, please open an issue with a feature request. I can add that in no problems. One thing is I want to keep the `createMapper()` API as simple as possible.
2. In older versions, AutoMapper will try to guess the type of `sourceObj` simply with `source || (sourceObj.constructor as Constructible<TSource>)`. Now `mapper.map()` might take in a `string` type as well. But it's not something I cannot fix with an overload. If passing in 3 arguments is not good enough for you, please create an issue as a feature request and I'll get to that. 

Thank you for trying it out :)

**Comment by nartc** [comment] 2021-01-05 13:37
Since @caiopiassali have tested and confirmed that it works with latest beta, I’m going to close this issue. 

Just a reminder, please check https://automapperts.netlify.app for info about the @automapper’s packages as well as migrations

**Closed by nartc** 2021-01-05 13:37 UTC
Labels: question
