### ISSUE TITLE
Any mapping always returns an empty object, without any errors

### ISSUE THREAD

**Issue by apiannikov** [nartc/mapper#149] opened 2020-06-14 16:40 UTC
## I'm submitting a...
<pre><code>
[ x ] Regression
[ ] Bug report
[ ] Feature request
[ ] Documentation issue or request
[ ] Support request
</code></pre>

## Current behavior
Any mapping always returns an empty object, without any errors

## Expected behavior
Correct mapping

## Minimal reproduction of the problem with instructions
In versions `@nartc/automapper@6.1.2`, `nestjsx-automapper@3.0.5` mapping works as expected.
In versions `@nartc/automapper@6.3.11`, `nestjsx-automapper@3.0.12` mapping returns `{}` (the same code).

## What is the motivation / use case for changing the behavior?
Incorrect behavior

## Environment
Windows 10
Nest.js
@nartc/automapper@6.3.11
nestjsx-automapper@3.0.12

**Comment by nartc** [comment] 2020-06-14 16:49
@apiannikov Thanks for reporting. What “simple mapping” are you referring to? And is 6.3.8 the last version working for you?

**Comment by apiannikov** [comment] 2020-06-14 16:58
@nartc, just any mapping to test. I just updated the packages to `@nartc/automapper@6.3.11` and `nestjsx-automapper@3.0.12`, and got the unexpected behavior.

Yes, `@nartc/automapper@6.3.8`, `nestjsx-automapper@3.0.12` are last versions that work.

**Comment by nartc** [comment] 2020-06-14 17:02
https://codesandbox.io/embed/automapper-demo-latest-42cg8?codemirror=1

This example still seems to work for me. Can you please provide a reproduce?

**Comment by apiannikov** [comment] 2020-06-14 17:27
@nartc, I just put some code,
[user entity](https://pastebin.com/vqhGVKiC)
[currentUser dto](https://pastebin.com/dpuJVxZh)
[custom mapper profile](https://pastebin.com/AGrkNYjS)
[app module with profile addition](https://pastebin.com/gjTGfVTa)
[mapping usage](https://pastebin.com/VjkgmKtZ)

**Comment by nartc** [comment] 2020-06-14 17:35
Thanks. I’ll take a look asap

**Comment by nartc** [comment] 2020-06-14 21:00
@apiannikov https://github.com/nartc/nestjsx-automapper-bug-149 I cannot reproduce the bug with the provided models + mapping configuration. I'm using `nestjsx-automapper@3.0.13` and `@nartc/automapper@6.3.11` (check `package.json`)

**Comment by apiannikov** [comment] 2020-06-15 08:59
Sorry for wasting your time. I checked imports of AutoMapper, they were all from `@nartc/automapper`, as described in [docs](https://automapper.netlify.app/docs/nest). And it worked till the version `6.3.11`. But now I've changed imports to `nestjsx-automapper` and it works.

**Comment by nartc** [comment] 2020-06-15 11:26
@apiannikov I see. That’s weird. Can you show the exact imports you used? maybe a TS3.9 problem since nestjsx-automapper just pass through some imports for ease of importing

**Comment by nartc** [comment] 2020-06-15 13:53
@apiannikov I have just tested by changing all imports to `@nartc/automapper` instead of `nestjsx-automapper`. I'm pretty confident that you'd had run into a problem with conflicting library version. Let me elaborate

`nestjsx-automapper` has a hard `dependencies` on `@nartc/automapper` which internally, `nestjsx-automapper` is dependent on specific version of `@nartc/automapper`. When you install `nestjsx-automapper`, `npm` will also install `@nartc/automapper` for you. 

`nestjsx-automapper@3.0.12` (prev version) does not have the latest `@nartc/automapper` version (6.3.11) just yet (1). If you install both `nestjsx-automapper` and `@nartc/automapper` in your project, you might run into version conflict because of reason stated above.

(1): I setup `nestjsx-automapper` dependencies update via `dependabot` which might be slow to pick up on latest version of `@nartc/automapper` at times :) Sorry for the inconvenience.

I am closing this issue. Please open a new one if you still run into issues :)

**Closed by nartc** 2020-06-15 13:53 UTC
Labels: awaiting reply
